server:
  port: 8088
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
multitenancy:
  master:
    datasource:
      url: jdbc:postgresql://localhost:5432/master_tenant
      username: postgres
      password:
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-master.yaml
  tenant:
    datasource:
      url-prefix: jdbc:postgresql://localhost:5432/
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-tenant.yaml
encryption:
  secret: very_secret
  salt: gau_gau
